using System.IO;
using System.Text;
using Microsoft.Web.WebView2.Core;

namespace WDM.Services;

public static class YouTubeCookieExporter
{
    public static string CookiePath => Path.Combine(TaskStore.AppDir, "youtube_cookies.txt");

    public static async Task<(string Path, int Count, bool SignedIn)> ExportAsync(CoreWebView2CookieManager manager)
    {
        var list = new List<CoreWebView2Cookie>();
        list.AddRange(await manager.GetCookiesAsync("https://www.youtube.com"));
        list.AddRange(await manager.GetCookiesAsync("https://www.google.com"));

        var selected = list
            .Where(c => IsGoogleDomain(c.Domain))
            .Where(c => c.Expires == default || c.Expires > DateTime.Now)
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Netscape HTTP Cookie File");
        sb.AppendLine("# Generated by Kivoy from your YouTube sign-in — do not edit.");
        foreach (var c in selected)
        {
            var domain = c.Domain.StartsWith('.') ? c.Domain : "." + c.Domain;
            var secure = c.IsSecure ? "TRUE" : "FALSE";
            var expires = c.Expires == default ? 0 : new DateTimeOffset(c.Expires.ToUniversalTime()).ToUnixTimeSeconds();
            sb.AppendLine($"{domain}\tTRUE\t{c.Path}\t{secure}\t{expires}\t{c.Name}\t{c.Value}");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(CookiePath)!);
        File.WriteAllText(CookiePath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var signedIn = selected.Any(c => c.Name is "LOGIN_INFO" or "SID" or "SSID" or "__Secure-3PSID");
        return (CookiePath, selected.Count, signedIn);
    }

    public static void SignOut()
    {
        if (File.Exists(CookiePath))
            File.Delete(CookiePath);
        var s = TaskStore.LoadSettings();
        if (s.YouTubeBrowserCookies == "wdm-native")
        {
            s.YouTubeBrowserCookies = "none";
            TaskStore.SaveSettings(s);
        }
    }

    private static bool IsGoogleDomain(string domain) =>
        domain.Contains("youtube.com", StringComparison.OrdinalIgnoreCase)
        || domain.Contains("google.com", StringComparison.OrdinalIgnoreCase)
        || domain.Contains("ytimg.com", StringComparison.OrdinalIgnoreCase);
}
