using System.IO;
using System.Text;
using Microsoft.Web.WebView2.Core;

namespace WDM.Services;

public static class YouTubeCookieExporter
{
    public static string CookiePath => Path.Combine(TaskStore.AppDir, "youtube_cookies.txt");

    public static async Task<(string Path, int Count, bool SignedIn)> ExportAsync(CoreWebView2CookieManager manager)
    {
        var list = new List<CoreWebView2Cookie>();
        list.AddRange(await manager.GetCookiesAsync("https://www.youtube.com"));
        list.AddRange(await manager.GetCookiesAsync("https://www.google.com"));

        var selected = list
            .Where(c => IsGoogleDomain(c.Domain))
            .Where(c => c.Expires == default || c.Expires > DateTime.Now)
            .DistinctBy(c => (c.Domain, c.Path, c.Name))
            .ToList();

        var sb = new StringBuilder();
        sb.AppendLine("# Netscape HTTP Cookie File");
        sb.AppendLine("# Generated by WDM from your YouTube sign-in — do not edit.");
        foreach (var c in selected)
        {
            var domain = c.Domain.StartsWith('.') ? c.Domain : "." + c.Domain;
            var secure = c.IsSecure ? "TRUE" : "FALSE";
            var expires = c.Expires == default ? 0 :
                (c.Expires.Kind == DateTimeKind.Unspecified
                    ? new DateTimeOffset(DateTime.SpecifyKind(c.Expires, DateTimeKind.Utc)).ToUnixTimeSeconds()
                    : new DateTimeOffset(c.Expires.ToUniversalTime()).ToUnixTimeSeconds());
            string path = SanitizeField(c.Path, "/");
            string name = SanitizeField(c.Name, "");
            string value = SanitizeField(c.Value, "");
            if (string.IsNullOrEmpty(name))
                continue;
            sb.AppendLine($"{domain}\tTRUE\t{path}\t{secure}\t{expires}\t{name}\t{value}");
        }

        Directory.CreateDirectory(Path.GetDirectoryName(CookiePath)!);
        File.WriteAllText(CookiePath, sb.ToString(), new UTF8Encoding(encoderShouldEmitUTF8Identifier: false));

        var signedIn = selected.Any(c => c.Name is "LOGIN_INFO" or "SID" or "SSID" or "__Secure-3PSID");
        return (CookiePath, selected.Count, signedIn);
    }

    public static void SignOut()
    {
        if (File.Exists(CookiePath))
            File.Delete(CookiePath);
        var s = TaskStore.LoadSettings();
        if (s.YouTubeBrowserCookies == "wdm-native")
        {
            s.YouTubeBrowserCookies = "none";
            TaskStore.SaveSettings(s);
        }
    }

    private static bool IsGoogleDomain(string domain)
    {
        if (string.IsNullOrWhiteSpace(domain))
            return false;
        domain = domain.Trim().TrimStart('.').ToLowerInvariant();
        return domain == "youtube.com" || domain.EndsWith(".youtube.com", StringComparison.Ordinal) ||
               domain == "google.com" || domain.EndsWith(".google.com", StringComparison.Ordinal) ||
               domain == "ytimg.com" || domain.EndsWith(".ytimg.com", StringComparison.Ordinal) ||
               domain == "youtu.be" || domain.EndsWith(".youtu.be", StringComparison.Ordinal);
    }

    /// <summary>Strips tab/CR/LF (Netscape field separators) so a malicious
    /// cookie value can't inject rogue lines into the file yt-dlp reads.</summary>
    private static string SanitizeField(string value, string fallback)
    {
        if (string.IsNullOrEmpty(value))
            return fallback;
        var sb = new StringBuilder(value.Length);
        foreach (char ch in value)
        {
            if (ch is '\r' or '\n' or '\t' or '\0')
                continue;
            sb.Append(ch);
        }
        string cleaned = sb.ToString();
        return cleaned.Length > 4096 ? cleaned[..4096] : cleaned;
    }
}
