#pragma checksum "..\..\..\..\AboutDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "9A8A36BF05D56DA30CF4617C7258D71A25000DE6"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WDM {
    
    
    /// <summary>
    /// AboutDialog
    /// </summary>
    public partial class AboutDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 30 "..\..\..\..\AboutDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock VersionText;
        
        #line default
        #line hidden
        
        
        #line 56 "..\..\..\..\AboutDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink KivoyLink;
        
        #line default
        #line hidden
        
        
        #line 65 "..\..\..\..\AboutDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Documents.Hyperlink TeleflowLink;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\AboutDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock UpdateStatusText;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\AboutDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CheckUpdateButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WDM;component/aboutdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\AboutDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.VersionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.KivoyLink = ((System.Windows.Documents.Hyperlink)(target));
            
            #line 56 "..\..\..\..\AboutDialog.xaml"
            this.KivoyLink.Click += new System.Windows.RoutedEventHandler(this.Link_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            this.TeleflowLink = ((System.Windows.Documents.Hyperlink)(target));
            
            #line 65 "..\..\..\..\AboutDialog.xaml"
            this.TeleflowLink.Click += new System.Windows.RoutedEventHandler(this.Link_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.UpdateStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            
            #line 76 "..\..\..\..\AboutDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseClick);
            
            #line default
            #line hidden
            return;
            case 6:
            this.CheckUpdateButton = ((System.Windows.Controls.Button)(target));
            
            #line 77 "..\..\..\..\AboutDialog.xaml"
            this.CheckUpdateButton.Click += new System.Windows.RoutedEventHandler(this.CheckUpdateClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

