#pragma checksum "..\..\..\..\OptionsDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "38FBEDA3A7BDF14B23B7A136DF60494C56A53201"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WDM {
    
    
    /// <summary>
    /// OptionsDialog
    /// </summary>
    public partial class OptionsDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 78 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelConnection;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ChunksBox;
        
        #line default
        #line hidden
        
        
        #line 100 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox MaxConcurrentBox;
        
        #line default
        #line hidden
        
        
        #line 111 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox RetriesBox;
        
        #line default
        #line hidden
        
        
        #line 121 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SpeedBox;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelFolders;
        
        #line default
        #line hidden
        
        
        #line 135 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FolderBox;
        
        #line default
        #line hidden
        
        
        #line 139 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RouteBox;
        
        #line default
        #line hidden
        
        
        #line 148 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox VideoFolderBox;
        
        #line default
        #line hidden
        
        
        #line 152 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MusicFolderBox;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox DocumentFolderBox;
        
        #line default
        #line hidden
        
        
        #line 166 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox CompressedFolderBox;
        
        #line default
        #line hidden
        
        
        #line 171 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ProgramFolderBox;
        
        #line default
        #line hidden
        
        
        #line 176 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelBrowser;
        
        #line default
        #line hidden
        
        
        #line 190 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock BrowserStatusText;
        
        #line default
        #line hidden
        
        
        #line 196 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelBehavior;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox ChecksumBox;
        
        #line default
        #line hidden
        
        
        #line 207 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox ScriptBox;
        
        #line default
        #line hidden
        
        
        #line 212 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox NotifyBox;
        
        #line default
        #line hidden
        
        
        #line 213 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox TrayProgressBox;
        
        #line default
        #line hidden
        
        
        #line 214 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox MinimizeToTrayBox;
        
        #line default
        #line hidden
        
        
        #line 215 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox RunAtStartupBox;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelYouTube;
        
        #line default
        #line hidden
        
        
        #line 231 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtStatusBadgeTitle;
        
        #line default
        #line hidden
        
        
        #line 232 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtStatusBadgeSub;
        
        #line default
        #line hidden
        
        
        #line 235 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button YtActivateBtn;
        
        #line default
        #line hidden
        
        
        #line 240 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border YtProgressCard;
        
        #line default
        #line hidden
        
        
        #line 243 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtProgressStatusText;
        
        #line default
        #line hidden
        
        
        #line 244 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtProgressPctText;
        
        #line default
        #line hidden
        
        
        #line 246 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar YtProgressBar;
        
        #line default
        #line hidden
        
        
        #line 251 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border YtPluginsCard;
        
        #line default
        #line hidden
        
        
        #line 262 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtDlpVersionText;
        
        #line default
        #line hidden
        
        
        #line 291 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border YtAuthCard;
        
        #line default
        #line hidden
        
        
        #line 296 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button NativeSignInBtn;
        
        #line default
        #line hidden
        
        
        #line 309 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelAppearance;
        
        #line default
        #line hidden
        
        
        #line 314 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox DarkModeBox;
        
        #line default
        #line hidden
        
        
        #line 320 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel PanelUpdates;
        
        #line default
        #line hidden
        
        
        #line 324 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox CheckForUpdatesBox;
        
        #line default
        #line hidden
        
        
        #line 330 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CurrentVersionText;
        
        #line default
        #line hidden
        
        
        #line 334 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock LatestVersionText;
        
        #line default
        #line hidden
        
        
        #line 336 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock UpdateStatusText;
        
        #line default
        #line hidden
        
        
        #line 338 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CheckNowButton;
        
        #line default
        #line hidden
        
        
        #line 339 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OpenReleaseButton;
        
        #line default
        #line hidden
        
        
        #line 340 "..\..\..\..\OptionsDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DownloadInstallButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WDM;component/optionsdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\OptionsDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 28 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 2:
            
            #line 34 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 40 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 4:
            
            #line 46 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 5:
            
            #line 52 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 6:
            
            #line 58 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 7:
            
            #line 64 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.RadioButton)(target)).Checked += new System.Windows.RoutedEventHandler(this.Tab_Checked);
            
            #line default
            #line hidden
            return;
            case 8:
            this.PanelConnection = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 9:
            this.ChunksBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 10:
            this.MaxConcurrentBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 11:
            this.RetriesBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 12:
            this.SpeedBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 13:
            this.PanelFolders = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 14:
            this.FolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 15:
            
            #line 136 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BrowseClick);
            
            #line default
            #line hidden
            return;
            case 16:
            this.RouteBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 17:
            this.VideoFolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 18:
            this.MusicFolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 19:
            this.DocumentFolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 20:
            this.CompressedFolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 21:
            this.ProgramFolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 22:
            this.PanelBrowser = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 23:
            this.BrowserStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 24:
            
            #line 192 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenExtensionHelper_Click);
            
            #line default
            #line hidden
            return;
            case 25:
            this.PanelBehavior = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 26:
            this.ChecksumBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 27:
            this.ScriptBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 28:
            
            #line 208 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.ScriptBrowseClick);
            
            #line default
            #line hidden
            return;
            case 29:
            this.NotifyBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 30:
            this.TrayProgressBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 31:
            this.MinimizeToTrayBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 32:
            this.RunAtStartupBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 33:
            this.PanelYouTube = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 34:
            this.YtStatusBadgeTitle = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 35:
            this.YtStatusBadgeSub = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 36:
            this.YtActivateBtn = ((System.Windows.Controls.Button)(target));
            
            #line 235 "..\..\..\..\OptionsDialog.xaml"
            this.YtActivateBtn.Click += new System.Windows.RoutedEventHandler(this.YtActivateBtn_Click);
            
            #line default
            #line hidden
            return;
            case 37:
            this.YtProgressCard = ((System.Windows.Controls.Border)(target));
            return;
            case 38:
            this.YtProgressStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 39:
            this.YtProgressPctText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 40:
            this.YtProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 41:
            this.YtPluginsCard = ((System.Windows.Controls.Border)(target));
            return;
            case 42:
            this.YtDlpVersionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 43:
            this.YtAuthCard = ((System.Windows.Controls.Border)(target));
            return;
            case 44:
            this.NativeSignInBtn = ((System.Windows.Controls.Button)(target));
            
            #line 302 "..\..\..\..\OptionsDialog.xaml"
            this.NativeSignInBtn.Click += new System.Windows.RoutedEventHandler(this.NativeSignInBtn_Click);
            
            #line default
            #line hidden
            return;
            case 45:
            this.PanelAppearance = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 46:
            this.DarkModeBox = ((System.Windows.Controls.CheckBox)(target));
            
            #line 314 "..\..\..\..\OptionsDialog.xaml"
            this.DarkModeBox.Checked += new System.Windows.RoutedEventHandler(this.DarkMode_Changed);
            
            #line default
            #line hidden
            
            #line 314 "..\..\..\..\OptionsDialog.xaml"
            this.DarkModeBox.Unchecked += new System.Windows.RoutedEventHandler(this.DarkMode_Changed);
            
            #line default
            #line hidden
            return;
            case 47:
            this.PanelUpdates = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 48:
            this.CheckForUpdatesBox = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 49:
            this.CurrentVersionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 50:
            this.LatestVersionText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 51:
            this.UpdateStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 52:
            this.CheckNowButton = ((System.Windows.Controls.Button)(target));
            
            #line 338 "..\..\..\..\OptionsDialog.xaml"
            this.CheckNowButton.Click += new System.Windows.RoutedEventHandler(this.CheckNowClick);
            
            #line default
            #line hidden
            return;
            case 53:
            this.OpenReleaseButton = ((System.Windows.Controls.Button)(target));
            
            #line 339 "..\..\..\..\OptionsDialog.xaml"
            this.OpenReleaseButton.Click += new System.Windows.RoutedEventHandler(this.OpenReleaseClick);
            
            #line default
            #line hidden
            return;
            case 54:
            this.DownloadInstallButton = ((System.Windows.Controls.Button)(target));
            
            #line 340 "..\..\..\..\OptionsDialog.xaml"
            this.DownloadInstallButton.Click += new System.Windows.RoutedEventHandler(this.DownloadInstallClick);
            
            #line default
            #line hidden
            return;
            case 55:
            
            #line 354 "..\..\..\..\OptionsDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

