#pragma checksum "..\..\..\..\TaskPropertiesDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0280D278B316D331BAF1B0BF36F5D513EE801393"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;
using WDM.ViewModels;


namespace WDM {
    
    
    /// <summary>
    /// TaskPropertiesDialog
    /// </summary>
    public partial class TaskPropertiesDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 22 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StatusText;
        
        #line default
        #line hidden
        
        
        #line 23 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FileNameText;
        
        #line default
        #line hidden
        
        
        #line 53 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock UrlText;
        
        #line default
        #line hidden
        
        
        #line 58 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FolderText;
        
        #line default
        #line hidden
        
        
        #line 62 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SizeText;
        
        #line default
        #line hidden
        
        
        #line 67 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBar;
        
        #line default
        #line hidden
        
        
        #line 68 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PercentText;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock SpeedText;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ChunksText;
        
        #line default
        #line hidden
        
        
        #line 81 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ResumeCapText;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock AddedText;
        
        #line default
        #line hidden
        
        
        #line 89 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CategoryText;
        
        #line default
        #line hidden
        
        
        #line 93 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock PriorityText;
        
        #line default
        #line hidden
        
        
        #line 97 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock HeadersText;
        
        #line default
        #line hidden
        
        
        #line 101 "..\..\..\..\TaskPropertiesDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ChecksumText;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WDM;component/taskpropertiesdialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\TaskPropertiesDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.StatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 2:
            this.FileNameText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            
            #line 50 "..\..\..\..\TaskPropertiesDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CopyUrlClick);
            
            #line default
            #line hidden
            return;
            case 4:
            this.UrlText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.FolderText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 6:
            this.SizeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 7:
            this.ProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 8:
            this.PercentText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.SpeedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.ChunksText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 11:
            this.ResumeCapText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 12:
            this.AddedText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 13:
            this.CategoryText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 14:
            this.PriorityText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 15:
            this.HeadersText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 16:
            this.ChecksumText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 17:
            
            #line 106 "..\..\..\..\TaskPropertiesDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FolderClick);
            
            #line default
            #line hidden
            return;
            case 18:
            
            #line 107 "..\..\..\..\TaskPropertiesDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CloseClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

