//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("background.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("background.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon128.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon16.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon32.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon48.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("manifest.json")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("media_sniffer.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.css")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.html")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("youtube_menu.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon128.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon16.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon32.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("icon48.png")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("manifest.json")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("media_sniffer.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.css")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.html")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("popup.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("youtube_menu.js")]
[assembly: System.Windows.Resources.AssemblyAssociatedContentFileAttribute("webview2loader.dll")]


