//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("WDM Team")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Release")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright © WDM Team")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("2.4.2.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("2.4.2.0+8b873281ba1dd10e21e47321ea2afb5707e70318")]
[assembly: System.Reflection.AssemblyProductAttribute("WDM")]
[assembly: System.Reflection.AssemblyTitleAttribute("WDM")]
[assembly: System.Reflection.AssemblyVersionAttribute("2.4.2.0")]
[assembly: System.Runtime.Versioning.TargetPlatformAttribute("Windows7.0")]
[assembly: System.Runtime.Versioning.SupportedOSPlatformAttribute("Windows7.0")]

// Generated by the MSBuild WriteCodeFragment class.

