#pragma checksum "..\..\..\..\WelcomeWindow.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "BF0C8D3B706C49A9C1E71469556242FDCFC68E47"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WDM {
    
    
    /// <summary>
    /// WelcomeWindow
    /// </summary>
    public partial class WelcomeWindow : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 52 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button CopyPathButton;
        
        #line default
        #line hidden
        
        
        #line 60 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock CopyFeedbackText;
        
        #line default
        #line hidden
        
        
        #line 74 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button ActivateBtn;
        
        #line default
        #line hidden
        
        
        #line 75 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button YouTubeBtn;
        
        #line default
        #line hidden
        
        
        #line 79 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ProgressCard;
        
        #line default
        #line hidden
        
        
        #line 82 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ProgressStatusText;
        
        #line default
        #line hidden
        
        
        #line 83 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ProgressPctText;
        
        #line default
        #line hidden
        
        
        #line 85 "..\..\..\..\WelcomeWindow.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ProgressBar ProgressBar;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WDM;component/welcomewindow.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\..\WelcomeWindow.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            
            #line 42 "..\..\..\..\WelcomeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FirefoxBtn_Click);
            
            #line default
            #line hidden
            return;
            case 2:
            this.CopyPathButton = ((System.Windows.Controls.Button)(target));
            
            #line 52 "..\..\..\..\WelcomeWindow.xaml"
            this.CopyPathButton.Click += new System.Windows.RoutedEventHandler(this.CopyPath_Click);
            
            #line default
            #line hidden
            return;
            case 3:
            
            #line 53 "..\..\..\..\WelcomeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.OpenExtensions_Click);
            
            #line default
            #line hidden
            return;
            case 4:
            this.CopyFeedbackText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 5:
            this.ActivateBtn = ((System.Windows.Controls.Button)(target));
            
            #line 74 "..\..\..\..\WelcomeWindow.xaml"
            this.ActivateBtn.Click += new System.Windows.RoutedEventHandler(this.ActivateBtn_Click);
            
            #line default
            #line hidden
            return;
            case 6:
            this.YouTubeBtn = ((System.Windows.Controls.Button)(target));
            
            #line 75 "..\..\..\..\WelcomeWindow.xaml"
            this.YouTubeBtn.Click += new System.Windows.RoutedEventHandler(this.YouTubeBtn_Click);
            
            #line default
            #line hidden
            return;
            case 7:
            this.ProgressCard = ((System.Windows.Controls.Border)(target));
            return;
            case 8:
            this.ProgressStatusText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.ProgressPctText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.ProgressBar = ((System.Windows.Controls.ProgressBar)(target));
            return;
            case 11:
            
            #line 99 "..\..\..\..\WelcomeWindow.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.FinishBtn_Click);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

