<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\WDM\Assets\WDM.ico</ApplicationIcon>
    <AssemblyName>WDM_Setup</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\WDM_Payload.zip">
      <Link>WDM_Payload.zip</Link>
    </EmbeddedResource>
  </ItemGroup>

</Project>
