#pragma checksum "..\..\..\AddDownloadDialog.xaml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "0731C8E6EFD54BE51DF2ADAA9C0A3DEB5972F61F"
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Windows;
using System.Windows.Automation;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Controls.Ribbon;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Forms.Integration;
using System.Windows.Ink;
using System.Windows.Input;
using System.Windows.Markup;
using System.Windows.Media;
using System.Windows.Media.Animation;
using System.Windows.Media.Effects;
using System.Windows.Media.Imaging;
using System.Windows.Media.Media3D;
using System.Windows.Media.TextFormatting;
using System.Windows.Navigation;
using System.Windows.Shapes;
using System.Windows.Shell;


namespace WDM {
    
    
    /// <summary>
    /// AddDownloadDialog
    /// </summary>
    public partial class AddDownloadDialog : System.Windows.Window, System.Windows.Markup.IComponentConnector {
        
        
        #line 29 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border FileCategoryBadge;
        
        #line default
        #line hidden
        
        
        #line 32 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FileCategoryIcon;
        
        #line default
        #line hidden
        
        
        #line 34 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock FileCategoryLabel;
        
        #line default
        #line hidden
        
        
        #line 59 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox UrlBox;
        
        #line default
        #line hidden
        
        
        #line 61 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border ProbeBadge;
        
        #line default
        #line hidden
        
        
        #line 64 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Image YtThumbnail;
        
        #line default
        #line hidden
        
        
        #line 71 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ProbeIcon;
        
        #line default
        #line hidden
        
        
        #line 73 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock ProbeText;
        
        #line default
        #line hidden
        
        
        #line 77 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock DuplicateWarning;
        
        #line default
        #line hidden
        
        
        #line 90 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox FolderBox;
        
        #line default
        #line hidden
        
        
        #line 99 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox NameBox;
        
        #line default
        #line hidden
        
        
        #line 105 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox CategoryBox;
        
        #line default
        #line hidden
        
        
        #line 117 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Border YouTubePanel;
        
        #line default
        #line hidden
        
        
        #line 125 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton YtTypeVideoAudio;
        
        #line default
        #line hidden
        
        
        #line 126 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton YtTypeVideoOnly;
        
        #line default
        #line hidden
        
        
        #line 127 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.RadioButton YtTypeAudioOnly;
        
        #line default
        #line hidden
        
        
        #line 137 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock YtQualityLabel;
        
        #line default
        #line hidden
        
        
        #line 138 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox YtQualityBox;
        
        #line default
        #line hidden
        
        
        #line 140 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel YtContainerPanel;
        
        #line default
        #line hidden
        
        
        #line 142 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox YtContainerBox;
        
        #line default
        #line hidden
        
        
        #line 151 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.StackPanel YtAudioFormatPanel;
        
        #line default
        #line hidden
        
        
        #line 153 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox YtAudioFormatBox;
        
        #line default
        #line hidden
        
        
        #line 162 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox YtEmbedThumb;
        
        #line default
        #line hidden
        
        
        #line 163 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox YtEmbedSubs;
        
        #line default
        #line hidden
        
        
        #line 164 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.CheckBox YtPlaylist;
        
        #line default
        #line hidden
        
        
        #line 181 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.ComboBox ChunksBox;
        
        #line default
        #line hidden
        
        
        #line 192 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox SpeedBox;
        
        #line default
        #line hidden
        
        
        #line 199 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox MirrorsBox;
        
        #line default
        #line hidden
        
        
        #line 206 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBox HeadersBox;
        
        #line default
        #line hidden
        
        
        #line 219 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.TextBlock StartHint;
        
        #line default
        #line hidden
        
        
        #line 222 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button OkButton;
        
        #line default
        #line hidden
        
        
        #line 224 "..\..\..\AddDownloadDialog.xaml"
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
        internal System.Windows.Controls.Button DownloadLaterButton;
        
        #line default
        #line hidden
        
        private bool _contentLoaded;
        
        /// <summary>
        /// InitializeComponent
        /// </summary>
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        public void InitializeComponent() {
            if (_contentLoaded) {
                return;
            }
            _contentLoaded = true;
            System.Uri resourceLocater = new System.Uri("/WDM;component/adddownloaddialog.xaml", System.UriKind.Relative);
            
            #line 1 "..\..\..\AddDownloadDialog.xaml"
            System.Windows.Application.LoadComponent(this, resourceLocater);
            
            #line default
            #line hidden
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("PresentationBuildTasks", "8.0.29.0")]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Design", "CA1033:InterfaceMethodsShouldBeCallableByChildTypes")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1800:DoNotCastUnnecessarily")]
        void System.Windows.Markup.IComponentConnector.Connect(int connectionId, object target) {
            switch (connectionId)
            {
            case 1:
            this.FileCategoryBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 2:
            this.FileCategoryIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 3:
            this.FileCategoryLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 4:
            this.UrlBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 59 "..\..\..\AddDownloadDialog.xaml"
            this.UrlBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.UrlBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 5:
            this.ProbeBadge = ((System.Windows.Controls.Border)(target));
            return;
            case 6:
            this.YtThumbnail = ((System.Windows.Controls.Image)(target));
            return;
            case 7:
            this.ProbeIcon = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 8:
            this.ProbeText = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 9:
            this.DuplicateWarning = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 10:
            this.FolderBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 11:
            
            #line 93 "..\..\..\AddDownloadDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.BrowseClick);
            
            #line default
            #line hidden
            return;
            case 12:
            this.NameBox = ((System.Windows.Controls.TextBox)(target));
            
            #line 99 "..\..\..\AddDownloadDialog.xaml"
            this.NameBox.TextChanged += new System.Windows.Controls.TextChangedEventHandler(this.NameBox_TextChanged);
            
            #line default
            #line hidden
            return;
            case 13:
            this.CategoryBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 105 "..\..\..\AddDownloadDialog.xaml"
            this.CategoryBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.CategoryBox_SelectionChanged);
            
            #line default
            #line hidden
            return;
            case 14:
            this.YouTubePanel = ((System.Windows.Controls.Border)(target));
            return;
            case 15:
            this.YtTypeVideoAudio = ((System.Windows.Controls.RadioButton)(target));
            
            #line 125 "..\..\..\AddDownloadDialog.xaml"
            this.YtTypeVideoAudio.Checked += new System.Windows.RoutedEventHandler(this.YtType_Changed);
            
            #line default
            #line hidden
            return;
            case 16:
            this.YtTypeVideoOnly = ((System.Windows.Controls.RadioButton)(target));
            
            #line 126 "..\..\..\AddDownloadDialog.xaml"
            this.YtTypeVideoOnly.Checked += new System.Windows.RoutedEventHandler(this.YtType_Changed);
            
            #line default
            #line hidden
            return;
            case 17:
            this.YtTypeAudioOnly = ((System.Windows.Controls.RadioButton)(target));
            
            #line 127 "..\..\..\AddDownloadDialog.xaml"
            this.YtTypeAudioOnly.Checked += new System.Windows.RoutedEventHandler(this.YtType_Changed);
            
            #line default
            #line hidden
            return;
            case 18:
            this.YtQualityLabel = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 19:
            this.YtQualityBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 20:
            this.YtContainerPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 21:
            this.YtContainerBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 22:
            this.YtAudioFormatPanel = ((System.Windows.Controls.StackPanel)(target));
            return;
            case 23:
            this.YtAudioFormatBox = ((System.Windows.Controls.ComboBox)(target));
            
            #line 153 "..\..\..\AddDownloadDialog.xaml"
            this.YtAudioFormatBox.SelectionChanged += new System.Windows.Controls.SelectionChangedEventHandler(this.YtAudioFormat_Changed);
            
            #line default
            #line hidden
            return;
            case 24:
            this.YtEmbedThumb = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 25:
            this.YtEmbedSubs = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 26:
            this.YtPlaylist = ((System.Windows.Controls.CheckBox)(target));
            return;
            case 27:
            this.ChunksBox = ((System.Windows.Controls.ComboBox)(target));
            return;
            case 28:
            this.SpeedBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 29:
            this.MirrorsBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 30:
            this.HeadersBox = ((System.Windows.Controls.TextBox)(target));
            return;
            case 31:
            this.StartHint = ((System.Windows.Controls.TextBlock)(target));
            return;
            case 32:
            this.OkButton = ((System.Windows.Controls.Button)(target));
            
            #line 223 "..\..\..\AddDownloadDialog.xaml"
            this.OkButton.Click += new System.Windows.RoutedEventHandler(this.OkClick);
            
            #line default
            #line hidden
            return;
            case 33:
            this.DownloadLaterButton = ((System.Windows.Controls.Button)(target));
            
            #line 225 "..\..\..\AddDownloadDialog.xaml"
            this.DownloadLaterButton.Click += new System.Windows.RoutedEventHandler(this.DownloadLaterClick);
            
            #line default
            #line hidden
            return;
            case 34:
            
            #line 226 "..\..\..\AddDownloadDialog.xaml"
            ((System.Windows.Controls.Button)(target)).Click += new System.Windows.RoutedEventHandler(this.CancelClick);
            
            #line default
            #line hidden
            return;
            }
            this._contentLoaded = true;
        }
    }
}

