<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WDM.Core\WDM.Core.csproj" />
    <ProjectReference Include="..\WDM.Media\WDM.Media.csproj" />
    <ProjectReference Include="..\WDM.Infrastructure\WDM.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="WDM" />
    <InternalsVisibleTo Include="WDM.Tests" />
    <InternalsVisibleTo Include="WDM.FunctionalTests" />
  </ItemGroup>

</Project>
